spring:
  application:
    name: demo
  main:
    banner-mode: off

server:
  servlet:
    context-path: /demo

management:
  server:
    port: 8081
    base-path: /
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0 # Set this lower on production - we don't need every single request traced!
#  metrics:
#    distribution:
#      percentiles-histogram:
#        http.server.requests: true # Enable to get histograms for every controller method
        #get_pokemon_by_name: true # Enable histograms for any methods tags @Observed(name="get_pokemon_by_name")
pokemon:
  base-url: https://pokeapi.co/api/v2/

owner: nathandeamer
