spring:
  application:
    name: demo

server:
  servlet:
    context-path: /demo

management:
  server:
    port: 8081
    base-path: /
  endpoints:
    web:
      exposure:
        include: "*"

pokemon:
  base-url: https://pokeapi.co/api/v2/

owner: nathandeamer

# Override logging level for test
logging:
  level:
    com.nathandeamer.demo.pokemon.PokemonController: debug
